### ISSUE TITLE
实际调用dubbo失败

### ISSUE THREAD

**Issue by ykdsg** [youzan/gatling-dubbo#3]
Failed to invoke remote method: getBrandById, provider: dubbo://**.**.**.**:28889/com.yt.icp.facade.BrandQueryFacade?applica...
没有其他的提示

**Comment by canyuns** [comment]
这是dubbo 调用本身的问题，检查下你的服务、还有客户端写的对不对

**Comment by ykdsg** [comment]
能把具体的日志给透传出来吗？这个信息太少了

**Comment by ykdsg** [comment]
补充下，使用的是dubbox，用具体main函数调用了下，有相应的报错信息了，
Caused by: com.alibaba.dubbo.remoting.RemotingException: Fail to decode request due to: RpcInvocation [methodName=getBrandById, parameterTypes=null, arguments=null, attachments={path=com.yt.icp.facade.BrandQueryFacade, input=436, dubbo=2.0.2, version=0.0.0}]
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:245)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:162)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:135)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:95)

**Comment by canyuns** [comment]
检查下你的传输参数中是否包含了不能序列化的属性

**Comment by qiangcaocao** [comment]
dubbo调通了 但是dubbo的返回结果是一个对象Result，然后报错说结果不能转换为Boolean：com.fasterxml.jackson.databind.JsonMappingException: cn.fraudmetrix.octopus.report.client.result.Result cannot be cast to java.lang.Boolean (through reference chain: io.gatling.commons.validation.Success["$mcZ$sp"])

Caused by: java.lang.ClassCastException: cn.fraudmetrix.octopus.report.client.result.Result cannot be cast to java.lang.Boolean
	at scala.runtime.BoxesRunTime.unboxToBoolean(BoxesRunTime.java:85)
	at io.gatling.commons.validation.Validation.get$mcZ$sp(Validation.scala:28)
	at io.gatling.commons.validation.Validation.get$mcZ$sp$(Validation.scala:28)
	at io.gatling.commons.validation.Success.get$mcZ$sp(Validation.scala:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:687)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	... 11 more

**Comment by canyuns** [comment]
看下 cn.fraudmetrix.octopus.report.client.result.Result 是怎么序列化的，Gatling 里面用的 jackson，如果你们不是 jackson，可能有兼容性问题

**Comment by qiangcaocao** [comment]
我们用的fastjson，那是不兼容了！ dubbo插件里面要更改吧 是改哪个地方啊？ 你们有交流群吗，有的话能拉我进去一下吗？我的QQ：860968698

**Comment by canyuns** [comment]
这个要改不容易，Gatling 里面全部用的 jackson；
没有交流群
