### ISSUE TITLE
java.lang.AbstractMethodError load abstract clock in DubboAction

### ISSUE THREAD

**Issue by markhuyong** [youzan/gatling-dubbo#4]
when use gatling sbt demo to load gatling-dubbo  meets error

```
16:05:20.318 [WARN ] c.a.d.c.s.e.SpringExtensionFactory -  [DUBBO] No spring extension (bean) named:defaultCompiler, try to find an extension (bean) of type java.lang.String, dubbo version: 2.6.5, current host: 192.168.4.74
16:05:20.323 [WARN ] c.a.d.c.s.e.SpringExtensionFactory -  [DUBBO] No spring extension (bean) named:defaultCompiler, type:java.lang.String found, stop get bean., dubbo version: 2.6.5, current host: 192.168.4.74
json file<function0>
Simulation computerdatabase.DubboTest started...
Uncaught error from thread [GatlingSystem-akka.actor.default-dispatcher-6]: Method io/gatling/dubbo/action/DubboAction.clock()Lio/gatling/commons/util/Clock; is abstract, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[GatlingSystem]
java.lang.AbstractMethodError: Method io/gatling/dubbo/action/DubboAction.clock()Lio/gatling/commons/util/Clock; is abstract
	at io.gatling.dubbo.action.DubboAction.clock(DubboAction.scala)
	at io.gatling.core.action.ExitableAction.$bang(BlockExit.scala:137)
	at io.gatling.core.action.ExitableAction.$bang$(BlockExit.scala:136)
	at io.gatling.dubbo.action.DubboAction.$bang(DubboAction.scala:21)
	at io.gatling.core.action.SingletonFeed$$anonfun$receive$1.applyOrElse(SingletonFeed.scala:67)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:25)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
16:05:21.182 [ERROR] a.a.ActorSystemImpl - Uncaught error from thread [GatlingSystem-akka.actor.default-dispatcher-6]: Method io/gatling/dubbo/action/DubboAction.clock()Lio/gatling/commons/util/Clock; is abstract, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[GatlingSystem]
java.lang.AbstractMethodError: Method io/gatling/dubbo/action/DubboAction.clock()Lio/gatling/commons/util/Clock; is abstract
	at io.gatling.dubbo.action.DubboAction.clock(DubboAction.scala)
	at io.gatling.core.action.ExitableAction.$bang(BlockExit.scala:137)
	at io.gatling.core.action.ExitableAction.$bang$(BlockExit.scala:136)
	at io.gatling.dubbo.action.DubboAction.$bang(DubboAction.scala:21)
	at io.gatling.core.action.SingletonFeed$$anonfun$receive$1.applyOrElse(SingletonFeed.scala:67)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:25)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] Simulation(s) execution ended.
```

**Comment by canyuns** [comment]
你是不是改了依赖的 gatling-core 的版本？这个错误看上去是依赖版本的问题。

**Comment by markhuyong** [comment]
有改
