### ISSUE TITLE
请教一下有遇到过下面的错误吗？按照demo；调用自己的服务时（spring-boot+dubbo），报错：

### ISSUE THREAD

**Issue by chris-tao** [youzan/gatling-dubbo#6]
Uncaught error from thread [GatlingSystem-akka.actor.default-dispatcher-6]: Method io/gatling/dubbo/action/DubboAction.clock()Lio/gatling/commons/util/Clock; is abstract, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[GatlingSystem]
java.lang.AbstractMethodError: Method io/gatling/dubbo/action/DubboAction.clock()Lio/gatling/commons/util/Clock; is abstract
        at io.gatling.dubbo.action.DubboAction.clock(DubboAction.scala)
        at io.gatling.core.action.ExitableAction.$bang(BlockExit.scala:140)
        at io.gatling.core.action.ExitableAction.$bang$(BlockExit.scala:139)
        at io.gatling.dubbo.action.DubboAction.$bang(DubboAction.scala:20)
        at io.gatling.core.action.SingletonFeed$$anonfun$receive$1.applyOrElse(SingletonFeed.scala:71)
        at akka.actor.Actor.aroundReceive(Actor.scala:539)
        at akka.actor.Actor.aroundReceive$(Actor.scala:537)
        at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:25)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
        at akka.actor.ActorCell.invoke(ActorCell.scala:581)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by wangyxt** [comment]
您好，我也碰到了，请问您解决了么？
